import os from 'os';

export const TUNING = {
  CLUSTER_WORKERS: 1, // hackathon mode — single process for simplicity

  // MongoDB
  MONGO_POOL_SIZE: 10,
  MONGO_MAX_IDLE_MS: 30_000,

  // Redis
  REDIS_POOL_SIZE: 5,

  // Gemini API
  GEMINI_MAX_CONCURRENT: 5,
  GEMINI_BATCH_SIZE: 10,
  GEMINI_BATCH_WAIT_MS: 200,
  GEMINI_RPM_LIMIT: 60,
  GEMINI_RETRY_ATTEMPTS: 3,
  GEMINI_RETRY_BASE_MS: 1000,

  // Claude API (chatbot)
  CLAUDE_MAX_CONCURRENT: 3,
  CLAUDE_TIMEOUT_MS: 15_000,

  // Scraping
  BROWSER_POOL_SIZE: 2,
  SCRAPE_CONCURRENCY_PER_CITY: 2,
  SCRAPE_PAGE_DELAY_MS: { min: 2000, max: 5000 },
  SCRAPE_MAX_PAGES_PER_CITY: 50,
  GITHUB_CONCURRENT_REPOS: 5,

  // BullMQ
  SCRAPE_QUEUE_CONCURRENCY: 3,
  NLP_QUEUE_CONCURRENCY: 5,
  RISK_RECALC_BATCH_SIZE: 50,

  // Caching TTL (seconds)
  CACHE_TTL_JOB_LISTINGS: 6 * 3600,
  CACHE_TTL_SKILLS_TRENDS: 3600,
  CACHE_TTL_VULNERABILITY: 1800,
  CACHE_TTL_COURSES: 7 * 86400,
  CACHE_TTL_GITHUB_PROFILE: 86400,

  // Socket.IO
  SOCKET_THROTTLE_MS: 500,
} as const;
